<?php
	$dbServer = 'localhost';
	$dbUsername = 'u392441939_firmas';
	$dbPassword = 'Timo2195';
	$dbDatabase = 'u392441939_firmas';
	$dbPort = '3306';
	$appURI = 'firmas';
	$host = 'localhost';

	$adminConfig = [
		'adminUsername' => "jacaraba",
		'adminPassword' => "\$2y\$10\$bM5f/IeSvnjcFO22WSxcZe6dt01AspIXA6E5CN2kq5hyp6bNjJszG",
		'senderEmail' => "jacaraba@hotmail.com",
		'notifyAdminNewMembers' => "",
		'defaultSignUp' => "1",
		'anonymousGroup' => "anonymous",
		'anonymousMember' => "guest",
		'groupsPerPage' => "10",
		'membersPerPage' => "10",
		'recordsPerPage' => "10",
		'custom1' => "Full Name",
		'custom2' => "Address",
		'custom3' => "City",
		'custom4' => "State",
		'MySQLDateFormat' => "%m/%d/%Y",
		'PHPDateFormat' => "n/j/Y",
		'PHPDateTimeFormat' => "m/d/Y, h:i a",
		'senderName' => "Membership management",
		'approvalSubject' => "Your membership is now approved",
		'approvalMessage' => "Dear member,\n\nYour membership is now approved by the admin. You can log in to your account here:\nhttp://localhost/firmas\n\nRegards,\nAdmin",
		'hide_twitter_feed' => "",
		'maintenance_mode_message' => "<b>Our website is currently down for maintenance</b><br>\r\nWe expect to be back in a couple hours. Thanks for your patience.",
		'mail_function' => "mail",
		'smtp_server' => "",
		'smtp_encryption' => "",
		'smtp_port' => "25",
		'smtp_user' => "",
		'smtp_pass' => "",
		'googleAPIKey' => "",
		'baseUploadPath' => "images",
	];