<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/firmas.php');
	include_once(__DIR__ . '/firmas_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('firmas');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'firmas';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`firmas`.`idfirma`" => "idfirma",
		"IF(    CHAR_LENGTH(`visita1`.`id`) || CHAR_LENGTH(`visita1`.`Nombre`), CONCAT_WS('',   `visita1`.`id`, `visita1`.`Nombre`), '') /* ID */" => "id",
		"`firmas`.`Imagen`" => "Imagen",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`firmas`.`idfirma`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`firmas`.`idfirma`" => "idfirma",
		"IF(    CHAR_LENGTH(`visita1`.`id`) || CHAR_LENGTH(`visita1`.`Nombre`), CONCAT_WS('',   `visita1`.`id`, `visita1`.`Nombre`), '') /* ID */" => "id",
		"`firmas`.`Imagen`" => "Imagen",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`firmas`.`idfirma`" => "ID",
		"IF(    CHAR_LENGTH(`visita1`.`id`) || CHAR_LENGTH(`visita1`.`Nombre`), CONCAT_WS('',   `visita1`.`id`, `visita1`.`Nombre`), '') /* ID */" => "ID",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`firmas`.`idfirma`" => "idfirma",
		"IF(    CHAR_LENGTH(`visita1`.`id`) || CHAR_LENGTH(`visita1`.`Nombre`), CONCAT_WS('',   `visita1`.`id`, `visita1`.`Nombre`), '') /* ID */" => "id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['id' => 'ID', ];

	$x->QueryFrom = "`firmas` LEFT JOIN `visita` as visita1 ON `visita1`.`id`=`firmas`.`id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'firmas_view.php';
	$x->TableTitle = 'Firmas';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`firmas`.`idfirma`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['ID', 'Imagen', ];
	$x->ColFieldName = ['id', 'Imagen', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/firmas_templateTV.html';
	$x->SelectedTemplate = 'templates/firmas_templateTVS.html';
	$x->TemplateDV = 'templates/firmas_templateDV.html';
	$x->TemplateDVP = 'templates/firmas_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: firmas_init
	$render = true;
	if(function_exists('firmas_init')) {
		$args = [];
		$render = firmas_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: firmas_header
	$headerCode = '';
	if(function_exists('firmas_header')) {
		$args = [];
		$headerCode = firmas_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: firmas_footer
	$footerCode = '';
	if(function_exists('firmas_footer')) {
		$args = [];
		$footerCode = firmas_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
