<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/visita.php');
	include_once(__DIR__ . '/visita_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('visita');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'visita';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`visita`.`id`" => "id",
		"`visita`.`Nombre`" => "Nombre",
		"`visita`.`latitud`" => "latitud",
		"`visita`.`longitud`" => "longitud",
		"`visita`.`direccion`" => "direccion",
		"if(`visita`.`fecha`,date_format(`visita`.`fecha`,'%m/%d/%Y %h:%i %p'),'')" => "fecha",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`visita`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`visita`.`fecha`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`visita`.`id`" => "id",
		"`visita`.`Nombre`" => "Nombre",
		"`visita`.`latitud`" => "latitud",
		"`visita`.`longitud`" => "longitud",
		"`visita`.`direccion`" => "direccion",
		"if(`visita`.`fecha`,date_format(`visita`.`fecha`,'%m/%d/%Y %h:%i %p'),'')" => "fecha",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`visita`.`id`" => "ID",
		"`visita`.`Nombre`" => "Nombre",
		"`visita`.`latitud`" => "Latitud",
		"`visita`.`longitud`" => "Longitud",
		"`visita`.`direccion`" => "Direccion",
		"`visita`.`fecha`" => "Fecha",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`visita`.`id`" => "id",
		"`visita`.`Nombre`" => "Nombre",
		"`visita`.`latitud`" => "latitud",
		"`visita`.`longitud`" => "longitud",
		"`visita`.`direccion`" => "direccion",
		"if(`visita`.`fecha`,date_format(`visita`.`fecha`,'%m/%d/%Y %h:%i %p'),'')" => "fecha",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`visita` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'visita_view.php';
	$x->TableTitle = 'Visita';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`visita`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Nombre', 'Latitud', 'Longitud', 'Direccion', 'Fecha', ];
	$x->ColFieldName = ['Nombre', 'latitud', 'longitud', 'direccion', 'fecha', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/visita_templateTV.html';
	$x->SelectedTemplate = 'templates/visita_templateTVS.html';
	$x->TemplateDV = 'templates/visita_templateDV.html';
	$x->TemplateDVP = 'templates/visita_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: visita_init
	$render = true;
	if(function_exists('visita_init')) {
		$args = [];
		$render = visita_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: visita_header
	$headerCode = '';
	if(function_exists('visita_header')) {
		$args = [];
		$headerCode = visita_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: visita_footer
	$footerCode = '';
	if(function_exists('visita_footer')) {
		$args = [];
		$footerCode = visita_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
